#!/usr/bin/env bash
# configures a new Ubuntu machine with respect to requirements
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i '25 i \\tadd_header X-Served-By $hostname;' /etc/nginx/nginx.conf
sudo service nginx restart
