#!/usr/bin/env bash
# Find out s keeping your Ubuntu s Nginx installation from listening on port 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
rm -rf /var/run/nginx.pidcontainerwhat