#!/usr/bin/env bash
# This script prints "Best School" ten times and "hi" on the ninth iteration
n=1

while [ $n -le 10 ]
do
	echo "Best School"
	if [ $n -eq 9 ]
	then
		echo "Hi"
		fi
		n=$(( n + 1 ))		
done