#!/usr/bin/env bash
# This script prints "bad luck" forth iteration, "good luck" on the eighth iteration
# and "Holberton School" for other iterations
n=1

while [ $n -le 20 ]
do
	echo $n
	case $n in
	
		4)
		   echo "bad luck from China"		
						;;
						
							9)
							
									echo "bad luck from Japan"
									
											;;
											
												17)
												
														echo "bad luck from Italy"
														
																;;
																
																	*)
																	
																			;;
																			
																			esac
																			
																			n=$(( n + 1 ))
											
done